spring.application.name=apollonia-dental

# Definicion de puerto, path de los endpoints
server.port=3800
server.servlet.context-path=/api/v1
spring.resources.add-mappings=false

# Definicion de los valores de la BD H2 - Atencion nombre de la BD: apollonia
spring.datasource.url=jdbc:h2:mem:apollonia
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.platform=h2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostraremos las operaciones SQL en BD
logging.level.org.springframework.jdbc.datasource.init.ScriptUtils=DEBUG
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=create
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

