spring.application.name=apollonia-dental

# Definición de puerto, path de los endpoints
server.port=3800
server.servlet.context-path=/api/v1
spring.web.resources.add-mappings=false

# Definición de los valores de la BD H2 - Atención nombre de la BD: apollonia
spring.datasource.url=jdbc:h2:mem:apollonia
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.platform=h2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.sql.init.schema-locations=classpath:import.sql

# Mostraremos las operaciones SQL en BD
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

